#------------
app:
    resource: '@AppBundle/Controller/'
    type: annotation
#------------
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
#------------
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
